### 前言
1. Numpy:數學運算的好幫手，取代List，類似Python內建的math
2. Scipy:Numpy的加強版，但我沒用過
3. Pandas:Python裡的Excel
4. Matplotlib:數據可視化的好幫手

### 1-1. 匯入import

In [1]:
# 完整匯入numpy
import numpy as np

np.random.rand(5)

array([0.12878719, 0.587087  , 0.80369867, 0.84507178, 0.83959875])

In [2]:
# 只從numpy匯入random
from numpy import random

random.rand(5)

array([0.57831437, 0.84975268, 0.62426481, 0.96068089, 0.34503383])

### 1-2. 環境設定magic command
僅能在Ipython/Jupyter使用，Spyder無法使用

In [3]:
# 接下來所有浮點數都只顯示到小數點第三位
%precision 3

'%.3f'

In [4]:
random.rand(5)

array([0.007, 0.785, 0.845, 0.02 , 0.657])

In [5]:
# 查指令，因為會跳出一堆東西，所以我先遮蔽
#%quickref

### 1-3. Numpy array
取代陣列List

In [6]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [7]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1-4. 查變數型態

In [9]:
data = np.array([1, 2, 3, 4, 5])
data.dtype

dtype('int32')

### 1-5. 查維度、長度

In [10]:
data = np.array([1, 2, 3, 4, 5])

In [11]:
# 維度
data.ndim

1

In [12]:
# 長度
# len(data)
data.size

5

In [13]:
# 每個維度的長度
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(data.shape)
print(data.shape[0])
print(data.shape[1])

(2, 3)
2
3


In [14]:
data.size

6

### 題外話:塑型

In [15]:
data = np.array([1, 2, 3, 4, 5, 6])
print(data)
print(data.reshape(2, 3))
print(data.reshape(3, -1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### 1-6. 四則運算

In [16]:
data = np.array([2, 4, 6])
print(data+10)
print(data-10)
print(data*10)
print(data/10)

[12 14 16]
[-8 -6 -4]
[20 40 60]
[0.2 0.4 0.6]


In [17]:
data1 = np.array([2, 4, 6])
data2 = np.array([1, 2, 3])

print(data1+data2)
print(data1-data2)
print(data1*data2)
print(data1/data2)

[3 6 9]
[1 2 3]
[ 2  8 18]
[2. 2. 2.]


### 1-7. 排序

In [18]:
data = np.random.rand(5)
print(data)

# 不改變data，我常用
print(np.sort(data))

# 直接改變data
data.sort()
data

[0.027 0.981 0.314 0.839 0.847]
[0.027 0.314 0.839 0.847 0.981]


array([0.027, 0.314, 0.839, 0.847, 0.981])

In [19]:
data = np.random.rand(5)
print(data)

# 不改變data
print(np.sort(data)[::-1])

# 直接改變data
data[::-1].sort()
data

[0.193 0.74  0.52  0.782 0.587]
[0.782 0.74  0.587 0.52  0.193]


array([0.782, 0.74 , 0.587, 0.52 , 0.193])

### 1-8. 最大、最小、總和、累積

In [20]:
data = np.array([1, 2, 3, 4, 5])

print(np.max(data))
print(np.min(data))
print(np.sum(data))
print(np.cumsum(data))

5
1
15
[ 1  3  6 10 15]


### 題外話. 最大值位置argmax、最小值位置argmin

In [21]:
data = np.array([1, 2, 3, 4, 5])

print(np.argmax(data))
print(np.argmin(data))

4
0


### 1-9. 亂數

In [22]:
# 常態分佈/正態分布/高斯亂數
print(np.random.randn(10))

# 均勻分佈，0~1
print(np.random.uniform(size=10))

# 整數亂數，0~4
print(np.random.randint(low=0, high=5, size=[5, 3]))

# 二元亂數
print(np.random.choice(2, 10))

[-1.075 -0.593  0.164 -1.547 -1.99  -1.43   0.724 -0.224 -2.243 -1.08 ]
[0.004 0.614 0.361 0.873 0.017 0.152 0.145 0.147 0.105 0.814]
[[3 1 0]
 [4 4 2]
 [2 3 0]
 [1 4 4]
 [2 3 2]]
[1 0 0 1 0 1 1 1 1 1]


In [23]:
# 自訂範圍、維度
np.random.uniform(low=-5, high=5, size=[5, 3])

array([[-0.51 , -4.576, -1.794],
       [ 1.375,  3.093, -0.309],
       [-4.568,  1.772, -4.755],
       [-2.26 ,  4.929,  4.755],
       [-0.873, -1.362, -1.304]])

### 題外話. 亂數種子
https://mjjoe1017.pixnet.net/blog/post/215512326-%5Bpython%5D-numpy.random.seed-%28--%29-%E7%94%A8%E6%B3%95

### 1-10. 隨機取樣

In [24]:
data = np.array([1, 2, 3, 4, 5])

# 從data中隨機取3個，會重複
print(np.random.choice(data, 3, replace=True))

# 從data中隨機取3個，不會重複
print(np.random.choice(data, 3, replace=False))

[3 5 2]
[5 2 1]


### 1-11. 矩陣乘法

In [25]:
data1 = np.arange(12).reshape(4, 3)
data2 = np.arange(12).reshape(4, 3)

# 逐元素乘
data1*data2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [26]:
data1 = np.arange(12).reshape(4, 3)
data2 = np.arange(12).reshape(3, 4)

# 線性代數
np.dot(data1, data2)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [27]:
### 1-12. 0矩陣或者1矩陣

print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


### 題外話. zeros_like, ones_like

In [28]:
data = np.arange(12).reshape(4, 3)

print(data)
print(np.zeros_like(data))
print(np.ones_like(data))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
